### ISSUE TITLE
Unplugging of headset not recognized

### ISSUE THREAD

**Issue by st3f-afk** [HelloVolla/android_kernel_volla_mt6763#6]
I hope that his is the right category for my first bug report.
The phone recognizes the plug in event of my head set. Pulling the plug out, leaves the phone thinking it is still connected - resulting in no audio output via the speakers.
Same error with headset and integrated mic - result in muted phone mic and no audio output of the phones speakers.
I grabbed the log from the plugging in, unplugging and then until turning off flight mode.

Volla Phone
PPR1.180610.011 dev-keys

```
11-19 12:23:05.042  2374  2374 I Telecom : WiredHeadsetManager: ACTION_HEADSET_PLUG event, plugged in: true, : WHC.oADA@AFA
11-19 12:23:05.044  2374  4480 I Telecom : CallAudioRouteStateMachine: Message received: CONNECT_WIRED_HEADSET=1, arg1=0: WHC.oADA->CARSM.pM_CONNECT_WIRED_HEADSET@AFA
11-19 12:23:05.044  2374  4480 I Telecom : QuiescentEarpieceRoute: Processing message CONNECT_WIRED_HEADSET: WHC.oADA->CARSM.pM_CONNECT_WIRED_HEADSET@AFA
11-19 12:23:05.045  2374  4480 I Telecom : Logging.Events: Non-call EVENT: AUDIO_ROUTE, Wired headset connected: WHC.oADA->CARSM.pM_CONNECT_WIRED_HEADSET@AFA
11-19 12:23:05.045  2374  4480 I Telecom : BluetoothRouteManager: getBluetoothAudioConnectedDevice: no headset service available.: WHC.oADA->CARSM.pM_CONNECT_WIRED_HEADSET@AFA
11-19 12:23:05.045  2866  3059 I vol.Events: writeEvent level_changed STREAM_MUSIC 5
11-19 12:23:05.046  2374  4480 I Telecom : CallAudioRouteStateMachine: Message received: SWITCH_HEADSET=1003, arg1=0: WHC.oADA->CARSM.pM_CONNECT_WIRED_HEADSET->CARSM.pM_SWITCH_HEADSET@AFA
11-19 12:23:05.046  2374  4480 I Telecom : QuiescentEarpieceRoute: Processing message SWITCH_HEADSET: WHC.oADA->CARSM.pM_CONNECT_WIRED_HEADSET->CARSM.pM_SWITCH_HEADSET@AFA
11-19 12:23:05.047  2374  4480 I Telecom : Logging.Events: Non-call EVENT: AUDIO_ROUTE, Leaving state QuiescentEarpieceRoute: WHC.oADA->CARSM.pM_CONNECT_WIRED_HEADSET->CARSM.pM_SWITCH_HEADSET@AFA
11-19 12:23:05.047  2374  4480 I Telecom : Logging.Events: Non-call EVENT: AUDIO_ROUTE, Entering state QuiescentHeadsetRoute: WHC.oADA->CARSM.pM_CONNECT_WIRED_HEADSET->CARSM.pM_SWITCH_HEADSET@AFA
11-19 12:23:05.047  2374  4480 I Telecom : BluetoothRouteManager: getBluetoothAudioConnectedDevice: no headset service available.: WHC.oADA->CARSM.pM_CONNECT_WIRED_HEADSET->CARSM.pM_SWITCH_HEADSET@AFA
11-19 12:23:05.053  2866  3059 I vol.Events: writeEvent level_changed STREAM_BLUETOOTH_SCO 7
11-19 12:23:06.832  2374  2737 I PowerManagerService: Waking up from sleep (uid=1000 reason=android.policy:POWER)...
11-19 12:23:06.833  2374  2374 W UsageStatsService: Event reported without a package name
11-19 12:23:06.838  2374  2400 I DisplayPowerController: Blocking screen on until initial contents have been drawn.
11-19 12:23:06.842  2122  2148 E         : flp_screen_monitor_thread: Screen on
11-19 12:23:06.846  2122  2148 E         : flp_screen_monitor_thread: Wake Monitor Restart
11-19 12:23:06.846  2374  2393 W KernelCpuProcReader: File not exist: /proc/uid_cpupower/time_in_state
11-19 12:23:06.849  2374  2393 W KernelCpuProcReader: File not exist: /proc/uid_cpupower/concurrent_active_time
11-19 12:23:06.850  2374  2393 W KernelCpuProcReader: File not exist: /proc/uid_cpupower/concurrent_policy_time
11-19 12:23:06.865  2374  2374 E MtkDataShapingUtils: Exception openLteGateByDataShaping  in java.lang.NullPointerException: null receiver
11-19 12:23:06.865  2374  2390 I WindowManager: Waiting for drawn Window{33558d2 u0 StatusBar}: removed=false visible=true mHasSurface=true drawState=1
11-19 12:23:06.865  2374  2374 W System.err: java.lang.NullPointerException: null receiver
11-19 12:23:06.869  2866  2866 W TemplateSliceBuilder: Not currently bunding a slice
11-19 12:23:06.869  2374  2712 I WindowManager: Waiting for drawn Window{33558d2 u0 StatusBar}: removed=false visible=true mHasSurface=true drawState=1
11-19 12:23:06.877  2374  2374 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
11-19 12:23:06.877  2374  2374 W System.err: 	at com.mediatek.server.MtkDataShaping.openLteGateByDataShaping(MtkDataShaping.java:36)
11-19 12:23:06.877  2374  2374 W System.err: 	at com.android.server.AlarmManagerService.deliverAlarmsLocked(AlarmManagerService.java:3607)
11-19 12:23:06.877  2374  2374 W System.err: 	at com.android.server.AlarmManagerService.interactiveStateChangedLocked(AlarmManagerService.java:3086)
11-19 12:23:06.877  2374  2374 W System.err: 	at com.android.server.AlarmManagerService$InteractiveStateReceiver.onReceive(AlarmManagerService.java:4007)
11-19 12:23:06.877  2374  2374 W System.err: 	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1391)
11-19 12:23:06.877  2374  2374 W System.err: 	at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
11-19 12:23:06.877  2374  2374 W System.err: 	at android.os.Handler.handleCallback(Handler.java:873)
11-19 12:23:06.877  2374  2374 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:99)
11-19 12:23:06.877  2374  2374 W System.err: 	at android.os.Looper.loop(Looper.java:193)
11-19 12:23:06.877  2374  2374 W System.err: 	at com.android.server.SystemServer.run(SystemServer.java:474)
11-19 12:23:06.877  2374  2374 W System.err: 	at com.android.server.SystemServer.main(SystemServer.java:304)
11-19 12:23:06.877  2374  2374 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
11-19 12:23:06.877  2374  2374 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
11-19 12:23:06.877  2374  2374 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:891)
11-19 12:23:06.877  2162  2162 I Light   : batch: handle:4, flag:0,samplingPeriodNs:250000000 maxBatchReportLatencyNs:0
11-19 12:23:06.879  2162  2162 I Light   : enable: handle:4, en:1 
11-19 12:23:06.888  2162  2162 I Proximity: batch: handle:7, flag:0,samplingPeriodNs:20000000 maxBatchReportLatencyNs:0
11-19 12:23:06.889  2162  2716 I Proximity: distance = 2
11-19 12:23:06.889  2162  2162 I Proximity: enable: handle:7, en:1 
11-19 12:23:06.902   417   437 I vendor.mediatek.hardware.power@2.0-impl: setInteractive Restore All
11-19 12:23:06.905  2162  2716 I Proximity: distance = 2
11-19 12:23:06.910  2374  2757 E WifiStateMachine: getWifiLinkLayerStats called without an interface
11-19 12:23:06.916  2374  2397 I DisplayManagerService: Display device changed state: "Integrierter Bildschirm", ON
11-19 12:23:06.926  2374  2737 I InputReader: Reconfiguring input devices.  changes=0x00000004
11-19 12:23:06.926  2374  2712 I WindowManager: Waiting for drawn Window{33558d2 u0 StatusBar}: removed=false visible=true mHasSurface=true drawState=1
11-19 12:23:06.940  2374  2712 I WindowManager: Waiting for drawn Window{33558d2 u0 StatusBar}: removed=false visible=true mHasSurface=true drawState=1
11-19 12:23:06.942   402   402 I hwcomposer: [HWC] Display(0) SetPowerMode(2)  
11-19 12:23:06.951  2866  2866 W ndroid.systemui: type=1400 audit(0.0:400): avc: denied { read } for name="u:object_r:vendor_default_prop:s0" dev="tmpfs" ino=1665 scontext=u:r:platform_app:s0:c512,c768 tcontext=u:object_r:vendor_default_prop:s0 tclass=file permissive=0
11-19 12:23:06.954  2866  2866 E libc    : Access denied finding property "vendor.sys.boot.reason"
11-19 12:23:06.959  2866  2866 W ndroid.systemui: type=1400 audit(0.0:401): avc: denied { read } for name="u:object_r:vendor_default_prop:s0" dev="tmpfs" ino=1665 scontext=u:r:platform_app:s0:c512,c768 tcontext=u:object_r:vendor_default_prop:s0 tclass=file permissive=0
11-19 12:23:06.963  2866  2866 E libc    : Access denied finding property "vendor.sys.boot.reason"
11-19 12:23:07.091   425   798 I BufferQueueProducer: [StatusBar#0](this:0x7c5bca2000,id:11,api:1,p:2866,c:425) queueBuffer: fps=0.02 dur=41874.12 max=41874.12 min=41874.12
11-19 12:23:07.103   425   798 I BufferQueueProducer: [ScreenDecorOverlay#0](this:0x7c60903800,id:12,api:1,p:2866,c:425) queueBuffer: fps=0.02 dur=49045.49 max=49045.49 min=49045.49
11-19 12:23:07.110  2374  2712 I WindowManager: Waiting for drawn Window{33558d2 u0 StatusBar}: removed=false visible=true mHasSurface=true drawState=4
11-19 12:23:07.112   425   798 I BufferQueueProducer: [ScreenDecorOverlayBottom#0](this:0x7c60ef8800,id:13,api:1,p:2866,c:425) queueBuffer: fps=0.02 dur=49049.58 max=49049.58 min=49049.58
11-19 12:23:07.115  2162  2716 I Accelerometer: batch: handle:0, flag:0,samplingPeriodNs:66667000 maxBatchReportLatencyNs:100000000
11-19 12:23:07.116  2162  2716 I Accelerometer: enable: handle:0, en:1
11-19 12:23:07.118  5536  5536 I libnfc_nci: [INFO:StNativeNfcManager.cpp(1921)] stNfcManager_doSetScreenState: state = 4 discovry_param = 1
11-19 12:23:07.120  2374  2400 I DisplayPowerController: Unblocked screen on after 283 ms
11-19 12:23:07.135   373  5739 W StNfcHal: ! i2cWrite!!, errno is 'I/O error'
11-19 12:23:07.143  2374  2400 W PowerManagerService: Screen on took 317 ms
11-19 12:23:07.144  5536  5723 I libnfc_nci: [INFO:StNativeNfcManager.cpp(767)] nfaDeviceManagementCallback: enter; event=0xB
11-19 12:23:07.144  5536  5723 I libnfc_nci: [INFO:StNativeNfcManager.cpp(897)] nfaDeviceManagementCallback: NFA_DM_SET_POWER_SUB_STATE_EVT; status=0x0
11-19 12:23:07.146  5536  5723 I libnfc_nci: [INFO:StNativeNfcManager.cpp(767)] nfaDeviceManagementCallback: enter; event=0x2
11-19 12:23:07.146  5536  5723 I libnfc_nci: [INFO:StNativeNfcManager.cpp(794)] nfaDeviceManagementCallback: NFA_DM_SET_CONFIG_EVT
11-19 12:23:07.146  5536  5723 I libnfc_nci: [INFO:NfcStExtensions.cpp(2955)] NfcStExtensions::notifyNciConfigCompletion: isGet = 0, length = 0x00
11-19 12:23:07.147   425   425 I BufferQueueConsumer: [ColorFade#0](this:0x7c5bc9f000,id:15,api:1,p:-1,c:-1) disconnect(C)
11-19 12:23:07.154   425   425 I BufferQueue: [ColorFade#0](this:0x7c5bc9f000,id:15,api:1,p:-1,c:-1) ~BufferQueueCore
11-19 12:23:07.157  2188  2240 I focaltech:hal:device: [ 173]:got 'FF_SCREEN_ON' event.
11-19 12:23:07.161   425   425 I SurfaceFlinger: [Built-in Screen (type:0)] fps:0.282489,dur:35399.62,max:35086.19,min:4.22
11-19 12:23:07.163  2374  3158 E TouchFilter: setTouchFilter LOG Enable prameter: 0
11-19 12:23:08.341  2183  2183 I sn      : Retry 10
11-19 12:23:08.342  2183  2183 I sn      : Fail to access err=2
11-19 12:23:08.342  2183  2183 I chatty  : uid=1000(system) /system/bin/sn identical 1 line
11-19 12:23:08.343  2183  2183 I sn      : Fail to access err=2
11-19 12:23:08.343  2183  2183 I sn      : Check all possible paths
11-19 12:23:08.388  2166  2166 I thermal_repeater: [recvMdThermalInfo] ret=5, strLen=127, ERROR
11-19 12:23:09.171  2374  2384 E TouchFilter: setTouchFilter LOG Enable prameter: 0
11-19 12:23:11.179  2374  3158 E TouchFilter: setTouchFilter LOG Enable prameter: 0
11-19 12:23:13.190  2374  3158 E TouchFilter: setTouchFilter LOG Enable prameter: 0
11-19 12:23:13.242  2162  2162 I Proximity: distance = 1
11-19 12:23:13.449  2162  2162 I Proximity: distance = 2
11-19 12:23:13.547  2374  2737 I PowerWrap: Loaded power HAL service
11-19 12:23:13.547  2374  2737 I PowerWrap: Link to death notification successful
11-19 12:23:13.547  2374  2737 I PowerWrap: PowerHal_TouchBoost
11-19 12:23:13.664   425   447 I BufferQueueProducer: [StatusBar#0](this:0x7c5bca2000,id:11,api:1,p:2866,c:425) queueBuffer: fps=0.91 dur=6573.83 max=6425.12 min=11.59
11-19 12:23:13.679   425   425 I SurfaceFlinger: [Built-in Screen (type:0)] fps:0.920460,dur:6518.48,max:6432.83,min:3.51
11-19 12:23:13.931  2374  2737 I PowerWrap: PowerHal_TouchBoost
11-19 12:23:15.197  2374  2384 E TouchFilter: setTouchFilter LOG Enable prameter: 0
11-19 12:23:15.417  2374  2737 I PowerWrap: PowerHal_TouchBoost
11-19 12:23:15.531  2374  2737 I PowerWrap: PowerHal_TouchBoost
11-19 12:23:15.552  2374  2777 I AudioTrack: AUDIO_OUTPUT_FLAG_FAST successful; frameCount 0 -> 4512
11-19 12:23:15.555  2374  2389 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.AIRPLANE_MODE flg=0x10 (has extras) } to com.mediatek.cellbroadcastreceiver/.CellBroadcastReceiver
11-19 12:23:15.556  4447  4447 I PhoneGlobals: Turning radio on - airplane

```

**Comment by nift4** [comment]
I think this should be an issue on the volla-os-beta-tests repo

**Comment by st3f-afk** [comment]
Thank you @nift4 for your hint. I sent my phone back in cause of it being likely a hardware defect. I'll close the bug.
